use crate::types::Language;

/// Check if a name is a built-in for the given language
pub fn is_builtin(name: &str, language: Language) -> bool {
    match language {
        Language::Python => PYTHON_BUILTINS.contains(&name),
        Language::JavaScript | Language::TypeScript | Language::Tsx | Language::Jsx => {
            JS_BUILTINS.contains(&name)
        }
        Language::Go => GO_BUILTINS.contains(&name),
        Language::Rust => RUST_BUILTINS.contains(&name),
        Language::C | Language::Cpp => is_c_external_builtin(name),
        Language::Esqlc => is_c_external_builtin(name) || ESQL_BUILTINS.contains(&name),
        Language::Shell => SHELL_BUILTINS.contains(&name),
    }
}

// Common C/POSIX/libc APIs. Treat these as external runtime/library symbols so
// resolution does not spend effort resolving calls like read(), malloc(), or
// pthread_mutex_lock() to unrelated project symbols. Generic callback synthesis
// still recognizes registrar APIs such as pthread_create() and signal().
const C_POSIX_LIBC_BUILTINS: &[&str] = &[
    // stdio
    "printf",
    "fprintf",
    "sprintf",
    "snprintf",
    "vprintf",
    "vfprintf",
    "vsprintf",
    "vsnprintf",
    "scanf",
    "fscanf",
    "sscanf",
    "fopen",
    "freopen",
    "fclose",
    "fflush",
    "fread",
    "fwrite",
    "fgetc",
    "getc",
    "getchar",
    "fgets",
    "fputc",
    "putc",
    "putchar",
    "fputs",
    "puts",
    "perror",
    "fseek",
    "ftell",
    "rewind",
    "feof",
    "ferror",
    "clearerr",
    "fileno",
    "fdopen",
    "remove",
    "rename",
    "tmpfile",
    "tmpnam",
    "setvbuf",
    "setbuf",
    "setlinebuf",
    "getline",
    "getdelim",
    "popen",
    "pclose",
    "flockfile",
    "funlockfile",
    "ftrylockfile",
    // memory / strings / ctype
    "malloc",
    "calloc",
    "realloc",
    "free",
    "aligned_alloc",
    "memcpy",
    "memmove",
    "memset",
    "memcmp",
    "memchr",
    "strlen",
    "strnlen",
    "strcpy",
    "strncpy",
    "strcat",
    "strncat",
    "strcmp",
    "strncmp",
    "strcasecmp",
    "strncasecmp",
    "strchr",
    "strrchr",
    "strstr",
    "strtok",
    "strtok_r",
    "strdup",
    "strndup",
    "strerror",
    "strerror_r",
    "atoi",
    "atol",
    "atoll",
    "strtol",
    "strtoll",
    "strtoul",
    "strtoull",
    "strtod",
    "strtof",
    "strtold",
    "abs",
    "labs",
    "llabs",
    "div",
    "ldiv",
    "lldiv",
    "rand",
    "srand",
    "drand48",
    "srand48",
    "arc4random",
    "arc4random_uniform",
    "arc4random_buf",
    "realpath",
    "va_start",
    "va_arg",
    "va_end",
    "va_copy",
    "_stricmp",
    "_strnicmp",
    "stricmp",
    "strnicmp",
    "MsiSetProperty",
    "Button_GetCheck",
    "mkstemp",
    "mkdtemp",
    "mktemp",
    "basename",
    "dirname",
    "isalnum",
    "isalpha",
    "isascii",
    "isblank",
    "iscntrl",
    "isdigit",
    "isgraph",
    "islower",
    "isprint",
    "ispunct",
    "isspace",
    "isupper",
    "isxdigit",
    "tolower",
    "toupper",
    // math
    "fabs",
    "fabsf",
    "fabsl",
    "floor",
    "floorf",
    "floorl",
    "ceil",
    "ceilf",
    "ceill",
    "round",
    "roundf",
    "roundl",
    "trunc",
    "truncf",
    "truncl",
    "sqrt",
    "sqrtf",
    "sqrtl",
    "pow",
    "powf",
    "powl",
    "exp",
    "expf",
    "expl",
    "log",
    "logf",
    "logl",
    "log10",
    "log10f",
    "log10l",
    "sin",
    "sinf",
    "sinl",
    "cos",
    "cosf",
    "cosl",
    "tan",
    "tanf",
    "tanl",
    "asin",
    "acos",
    "atan",
    "atan2",
    "isnan",
    "isinf",
    "isfinite",
    // POSIX file/directory I/O
    "open",
    "openat",
    "creat",
    "close",
    "read",
    "write",
    "pread",
    "pwrite",
    "readv",
    "writev",
    "lseek",
    "fsync",
    "fdatasync",
    "fcntl",
    "ioctl",
    "stat",
    "fstat",
    "lstat",
    "fstatat",
    "access",
    "faccessat",
    "chmod",
    "fchmod",
    "chown",
    "fchown",
    "umask",
    "link",
    "symlink",
    "readlink",
    "unlink",
    "unlinkat",
    "mkdir",
    "mkdirat",
    "rmdir",
    "opendir",
    "fdopendir",
    "readdir",
    "readdir_r",
    "closedir",
    "rewinddir",
    "telldir",
    "seekdir",
    "chdir",
    "fchdir",
    "getcwd",
    "truncate",
    "ftruncate",
    "dup",
    "dup2",
    "dup3",
    "pipe",
    "pipe2",
    "poll",
    "select",
    "pselect",
    "kqueue",
    "kevent",
    "epoll_create",
    "epoll_create1",
    "epoll_ctl",
    "epoll_wait",
    "inotify_init",
    "inotify_init1",
    "inotify_add_watch",
    "inotify_rm_watch",
    "flock",
    "lockf",
    // process control
    "fork",
    "vfork",
    "execve",
    "execl",
    "execlp",
    "execle",
    "execv",
    "execvp",
    "execvpe",
    "_exit",
    "exit",
    "atexit",
    "abort",
    "wait",
    "waitpid",
    "waitid",
    "system",
    "getpid",
    "getppid",
    "getuid",
    "geteuid",
    "getgid",
    "getegid",
    "setuid",
    "seteuid",
    "setgid",
    "setegid",
    "getenv",
    "setenv",
    "unsetenv",
    "putenv",
    "clearenv",
    "daemon",
    "setsid",
    "getsid",
    "setpgid",
    "getpgid",
    "getpgrp",
    "nice",
    "setpriority",
    "getpriority",
    // signals
    "signal",
    "sigaction",
    "sigemptyset",
    "sigfillset",
    "sigaddset",
    "sigdelset",
    "sigismember",
    "sigprocmask",
    "pthread_sigmask",
    "kill",
    "raise",
    "alarm",
    "pause",
    "sigsuspend",
    "sigwait",
    "sigwaitinfo",
    "sigtimedwait",
    // pthreads
    "pthread_create",
    "pthread_join",
    "pthread_detach",
    "pthread_exit",
    "pthread_self",
    "pthread_equal",
    "pthread_once",
    "pthread_mutex_init",
    "pthread_mutex_destroy",
    "pthread_mutex_lock",
    "pthread_mutex_trylock",
    "pthread_mutex_timedlock",
    "pthread_mutex_unlock",
    "pthread_rwlock_init",
    "pthread_rwlock_destroy",
    "pthread_rwlock_rdlock",
    "pthread_rwlock_tryrdlock",
    "pthread_rwlock_wrlock",
    "pthread_rwlock_trywrlock",
    "pthread_rwlock_unlock",
    "pthread_cond_init",
    "pthread_cond_destroy",
    "pthread_cond_wait",
    "pthread_cond_timedwait",
    "pthread_cond_signal",
    "pthread_cond_broadcast",
    "pthread_key_create",
    "pthread_key_delete",
    "pthread_getspecific",
    "pthread_setspecific",
    "pthread_attr_init",
    "pthread_attr_destroy",
    "pthread_attr_setdetachstate",
    "pthread_attr_getdetachstate",
    "pthread_attr_setstacksize",
    "pthread_attr_getstacksize",
    "pthread_barrier_init",
    "pthread_barrier_destroy",
    "pthread_barrier_wait",
    "sem_init",
    "sem_destroy",
    "sem_wait",
    "sem_trywait",
    "sem_post",
    // sockets/networking
    "socket",
    "socketpair",
    "bind",
    "listen",
    "accept",
    "accept4",
    "connect",
    "send",
    "recv",
    "sendto",
    "recvfrom",
    "sendmsg",
    "recvmsg",
    "setsockopt",
    "getsockopt",
    "shutdown",
    "getaddrinfo",
    "freeaddrinfo",
    "gai_strerror",
    "getnameinfo",
    "inet_ntop",
    "inet_pton",
    "inet_addr",
    "inet_aton",
    "htons",
    "htonl",
    "ntohs",
    "ntohl",
    "gethostbyname",
    "gethostbyaddr",
    "gethostname",
    "sethostname",
    "if_nametoindex",
    "if_indextoname",
    // time
    "time",
    "clock",
    "clock_gettime",
    "clock_settime",
    "gettimeofday",
    "settimeofday",
    "nanosleep",
    "sleep",
    "usleep",
    "localtime",
    "localtime_r",
    "gmtime",
    "gmtime_r",
    "mktime",
    "strftime",
    "strptime",
    "difftime",
    "ctime",
    "ctime_r",
    "asctime",
    "asctime_r",
    "tzset",
    "timer_create",
    "timer_delete",
    "timer_settime",
    "timer_gettime",
    // mmap / dynamic loading / misc
    "mmap",
    "munmap",
    "mprotect",
    "msync",
    "mlock",
    "munlock",
    "dlopen",
    "dlsym",
    "dlclose",
    "dlerror",
    "qsort",
    "bsearch",
    "assert",
    // Win32 / MFC common APIs. These show up heavily in cross-platform C/C++
    // trees and should be treated like external SDK calls, not project symbols.
    "GetDlgItem",
    "LoadString",
    "EnableWindow",
    "ShowWindow",
    "SendMessage",
    "PostMessage",
    "GetParent",
    "SetParent",
    "GetWindowText",
    "GetWindowTextA",
    "GetWindowTextW",
    "SetWindowText",
    "SetWindowTextA",
    "SetWindowTextW",
    "GetWindowLong",
    "GetWindowLongPtr",
    "SetWindowLong",
    "SetWindowLongPtr",
    "GetModuleHandle",
    "GetModuleHandleA",
    "GetModuleHandleW",
    "GetProcAddress",
    "CreateFile",
    "CreateFileA",
    "CreateFileW",
    "ReadFile",
    "WriteFile",
    "CloseHandle",
    "DeleteFile",
    "DeleteFileA",
    "DeleteFileW",
    "MoveFile",
    "CopyFile",
    "CreateDirectory",
    "RemoveDirectory",
    "FindFirstFile",
    "FindNextFile",
    "FindClose",
    "CreateWindow",
    "CreateWindowEx",
    "DestroyWindow",
    "UpdateWindow",
    "InvalidateRect",
    "MessageBox",
    "MessageBoxA",
    "MessageBoxW",
    "DialogBox",
    "DialogBoxParam",
    "EndDialog",
    "DefWindowProc",
    "RegisterClass",
    "RegisterClassEx",
    "GetMessage",
    "TranslateMessage",
    "DispatchMessage",
    "PeekMessage",
    "LoadIcon",
    "LoadCursor",
    "LoadMenu",
    "SetTimer",
    "KillTimer",
    "GetDC",
    "ReleaseDC",
    "BeginPaint",
    "EndPaint",
    "CreateCompatibleDC",
    "DeleteDC",
    "SelectObject",
    "DeleteObject",
    "GetStockObject",
    "SetForegroundWindow",
    "SetFocus",
    "GetFocus",
    "GetLastError",
    "SetLastError",
    "FormatMessage",
    "MultiByteToWideChar",
    "WideCharToMultiByte",
    "lstrcpy",
    "lstrcpyA",
    "lstrcpyW",
    "lstrcpyn",
    "lstrcat",
    "lstrcmp",
    "lstrcmpi",
    "lstrlen",
    "AfxMessageBox",
    // MFC CString/CWnd/CList/CArray/DDX helpers and common generated message-map
    // methods. These are methods/macros supplied by MFC rather than project
    // symbols in most legacy Windows codebases.
    "Format",
    "AddTail",
    "RemoveHead",
    "GetHeadPosition",
    "GetNext",
    "GetAt",
    "GetItemCount",
    "GetItemData",
    "CompareNoCase",
    "ConcatStr",
    "IsEmpty",
    "IsWindow",
    "IsKindOf",
    "IsStoring",
    "Serialize",
    "DoDataExchange",
    "DDX_Control",
    "DDX_Text",
    "UpdateData",
    "InvokeHelper",
    "MoveWindow",
    "GetClientRect",
    "ResetDisplay",
    "OnInitDialog",
    // Windows installer/registry APIs.
    "MsiGetProperty",
    "MsiGetPropertyA",
    "MsiGetPropertyW",
    "RegOpenKey",
    "RegOpenKeyEx",
    "RegCreateKey",
    "RegCreateKeyEx",
    "RegCloseKey",
    "RegQueryValue",
    "RegQueryValueEx",
    "RegSetValue",
    "RegSetValueEx",
    "RegDeleteKey",
    "RegDeleteValue",
    // TCHAR portability aliases.
    "_stprintf",
    "_sntprintf",
    "_tcscpy",
    "_tcsncpy",
    "_tcscat",
    "_tcscmp",
    "_tcsicmp",
    "_tcslen",
];

const ESQL_BUILTINS: &[&str] = &[
    // Embedded SQL/C grammar often captures SQL scalar functions/types as calls.
    "varchar",
    "date",
    "mod",
    "count",
    "sum",
    "avg",
    "min",
    "max",
    "substr",
    "substring",
    "trim",
    "upper",
    "lower",
];

fn is_c_external_builtin(name: &str) -> bool {
    C_POSIX_LIBC_BUILTINS.contains(&name)
        || C_EXTERNAL_PREFIXES
            .iter()
            .any(|prefix| name.starts_with(prefix))
}

// Common third-party C GUI/runtime library prefixes. Keep this conservative:
// these prefixes identify external APIs in large legacy C/C++ applications, and
// avoiding per-call resolution prevents huge unresolved queues.
const C_EXTERNAL_PREFIXES: &[&str] = &[
    "gtk_",
    "Gtk",
    "gdk_",
    "g_object_",
    "g_signal_",
    "g_list_",
    "g_slist_",
    "g_hash_table_",
    "g_malloc",
    "g_free",
    "g_strdup",
    "Xt",
    "Xm",
    "CWnd::",
    "CString::",
    "GetWindow",
    "SetWindow",
    "ScreenToClient",
    "Exception",
    "JNI",
];

const SHELL_BUILTINS: &[&str] = &[
    "cd", "echo", "export", "local", "readonly", "shift", "test", "true", "false", "printf",
    "read", "return", "source", "set", "unset", "trap", "type", "ulimit", "umask", "wait", "exit",
    "break", "continue", "eval", "exec",
    // Common POSIX command-line tools that shell extraction sees as calls.
    "grep", "egrep", "fgrep", "sed", "awk", "cat", "cut", "sort", "uniq", "find", "xargs", "rm",
    "mv", "cp", "mkdir", "rmdir", "chmod", "chown", "ln", "pwd", "dirname", "basename", "head",
    "tail", "wc", "tr", "tee", "date", "sleep", "kill", "ps", "expr", "printf",
];

// Python built-ins
const PYTHON_BUILTINS: &[&str] = &[
    "print",
    "len",
    "range",
    "str",
    "int",
    "float",
    "list",
    "dict",
    "set",
    "tuple",
    "bool",
    "type",
    "isinstance",
    "issubclass",
    "hasattr",
    "getattr",
    "setattr",
    "delattr",
    "callable",
    "repr",
    "abs",
    "all",
    "any",
    "bin",
    "bool",
    "bytes",
    "bytearray",
    "chr",
    "complex",
    "dir",
    "divmod",
    "enumerate",
    "eval",
    "exec",
    "filter",
    "format",
    "frozenset",
    "globals",
    "hash",
    "help",
    "hex",
    "id",
    "input",
    "iter",
    "map",
    "max",
    "min",
    "next",
    "object",
    "oct",
    "open",
    "ord",
    "pow",
    "property",
    "round",
    "slice",
    "sorted",
    "sum",
    "super",
    "vars",
    "zip",
    "None",
    "True",
    "False",
    "Ellipsis",
    "NotImplemented",
    "append",
    "extend",
    "pop",
    "insert",
    "remove",
    "sort",
    "reverse",
    "copy",
    "keys",
    "values",
    "items",
    "get",
    "update",
    "setdefault",
    "clear",
    "add",
    "remove",
    "discard",
    "union",
    "intersection",
    "difference",
    "join",
    "split",
    "strip",
    "lower",
    "upper",
    "replace",
    "find",
    "startswith",
    "endswith",
];

// JavaScript/TypeScript built-ins
const JS_BUILTINS: &[&str] = &[
    "console",
    "window",
    "document",
    "process",
    "require",
    "module",
    "exports",
    "Promise",
    "Array",
    "Object",
    "String",
    "Number",
    "Boolean",
    "Function",
    "RegExp",
    "Date",
    "Error",
    "Math",
    "JSON",
    "Map",
    "Set",
    "WeakMap",
    "WeakSet",
    "Symbol",
    "Proxy",
    "Reflect",
    "Intl",
    "NaN",
    "Infinity",
    "undefined",
    "parseInt",
    "parseFloat",
    "isNaN",
    "isFinite",
    "encodeURI",
    "decodeURI",
    "encodeURIComponent",
    "decodeURIComponent",
    "eval",
    "setTimeout",
    "setInterval",
    "clearTimeout",
    "clearInterval",
    "fetch",
    "await",
    "async",
    "let",
    "const",
    "class",
    "extends",
    "super",
    "this",
    "new",
    "typeof",
    "instanceof",
    "void",
    "delete",
    "throw",
    "try",
    "catch",
    "finally",
    "if",
    "else",
    "for",
    "while",
    "do",
    "switch",
    "case",
    "break",
    "continue",
    "return",
    "with",
    "try",
    "Buffer",
    "URL",
    "URLSearchParams",
    "Headers",
    "Request",
    "Response",
];

// Go built-ins
const GO_BUILTINS: &[&str] = &[
    "make", "new", "len", "cap", "append", "copy", "delete", "panic", "recover", "print",
    "println", "error", "true", "false", "iota", "nil", "append", "cap", "close", "complex",
    "imag", "real", "copy", "delete", "len", "make", "new", "panic", "recover", "append", "cap",
    "close", "complex", "imag", "real", "fmt", "os", "io", "net", "http", "json", "encoding",
    "log", "sync", "context", "time", "math", "strings", "strconv", "bytes", "bufio",
];

// Rust built-ins (prelude + std/core common items)
const RUST_BUILTINS: &[&str] = &[
    "Some",
    "None",
    "Ok",
    "Err",
    "true",
    "false",
    "std",
    "core",
    "alloc",
    "vec",
    "string",
    "stringify",
    "println",
    "eprintln",
    "print",
    "eprint",
    "format",
    "panic",
    "unreachable",
    "unimplemented",
    "todo",
    "assert",
    "assert_eq",
    "assert_ne",
    "debug_assert",
    "debug_assert_eq",
    "debug_assert_ne",
    "derive",
    "macro_rules",
    "use",
    "pub",
    "mod",
    "crate",
    "self",
    "super",
    "Option",
    "Result",
    "Vec",
    "String",
    "Vec",
    "HashMap",
    "HashSet",
    "Box",
    "Rc",
    "Arc",
    "Cell",
    "RefCell",
    "Mutex",
    "RwLock",
    "Condvar",
    "Drop",
    "Clone",
    "Copy",
    "PartialEq",
    "PartialOrd",
    "Eq",
    "Ord",
    "Default",
    "Debug",
    "Display",
    "Hash",
    "Borrow",
    "Into",
    "From",
    "Iterator",
    "IntoIterator",
    "Extend",
    "DoubleEndedIterator",
    "Future",
    "Async",
    "await",
    "yield",
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn c_varargs_and_win32_names_are_external() {
        for name in [
            "va_start",
            "va_arg",
            "va_end",
            "_stricmp",
            "MsiSetProperty",
            "Button_GetCheck",
        ] {
            assert!(is_builtin(name, Language::C), "{name}");
            assert!(is_builtin(name, Language::Cpp), "{name}");
            assert!(is_builtin(name, Language::Esqlc), "{name}");
        }
    }

    #[test]
    fn c_posix_libc_builtins_are_external() {
        for name in [
            "malloc",
            "free",
            "open",
            "read",
            "write",
            "close",
            "pthread_create",
            "pthread_mutex_lock",
            "signal",
            "sigaction",
            "socket",
            "accept",
            "fork",
            "execvp",
            "waitpid",
            "mmap",
            "dlopen",
            "abs",
            "GetDlgItem",
            "LoadString",
            "EnableWindow",
            "AfxMessageBox",
            "gtk_widget_show",
            "g_signal_connect",
            "XtVaAppInitialize",
            "XmCreateForm",
        ] {
            assert!(is_builtin(name, Language::C), "{name}");
            assert!(is_builtin(name, Language::Cpp), "{name}");
            assert!(is_builtin(name, Language::Esqlc), "{name}");
        }
    }

    #[test]
    fn shell_exit_is_external() {
        assert!(is_builtin("exit", Language::Shell));
    }

    #[test]
    fn shell_common_commands_are_external() {
        for name in ["grep", "sed", "awk", "cat", "find"] {
            assert!(is_builtin(name, Language::Shell), "{name}");
        }
    }

    #[test]
    fn esql_scalar_tokens_are_external() {
        for name in ["varchar", "date", "mod"] {
            assert!(is_builtin(name, Language::Esqlc), "{name}");
            assert!(!is_builtin(name, Language::C), "{name}");
        }
    }

    #[test]
    fn c_posix_names_do_not_bleed_into_other_languages() {
        assert!(!is_builtin("pthread_create", Language::Python));
        assert!(!is_builtin("malloc", Language::Rust));
    }
}
