use crate::types::Language;

/// Check if a name is a built-in for the given language
pub fn is_builtin(name: &str, language: Language) -> bool {
    match language {
        Language::Python => PYTHON_BUILTINS.contains(&name),
        Language::JavaScript | Language::TypeScript | Language::Tsx | Language::Jsx => {
            JS_BUILTINS.contains(&name)
        }
        Language::Go => GO_BUILTINS.contains(&name),
        Language::Rust => RUST_BUILTINS.contains(&name),
        Language::C | Language::Cpp | Language::Esqlc => {
            // C/C++ has no built-in set (stdlib functions are resolved differently)
            false
        }
        Language::Shell => SHELL_BUILTINS.contains(&name),
    }
}

const SHELL_BUILTINS: &[&str] = &[
    "cd", "echo", "export", "local", "readonly", "shift", "test", "true", "false", "printf",
    "read", "return", "source", "set", "unset", "trap", "type", "ulimit", "umask", "wait",
];

// Python built-ins
const PYTHON_BUILTINS: &[&str] = &[
    "print",
    "len",
    "range",
    "str",
    "int",
    "float",
    "list",
    "dict",
    "set",
    "tuple",
    "bool",
    "type",
    "isinstance",
    "issubclass",
    "hasattr",
    "getattr",
    "setattr",
    "delattr",
    "callable",
    "repr",
    "abs",
    "all",
    "any",
    "bin",
    "bool",
    "bytes",
    "bytearray",
    "chr",
    "complex",
    "dir",
    "divmod",
    "enumerate",
    "eval",
    "exec",
    "filter",
    "format",
    "frozenset",
    "globals",
    "hash",
    "help",
    "hex",
    "id",
    "input",
    "iter",
    "map",
    "max",
    "min",
    "next",
    "object",
    "oct",
    "open",
    "ord",
    "pow",
    "property",
    "round",
    "slice",
    "sorted",
    "sum",
    "super",
    "vars",
    "zip",
    "None",
    "True",
    "False",
    "Ellipsis",
    "NotImplemented",
    "append",
    "extend",
    "pop",
    "insert",
    "remove",
    "sort",
    "reverse",
    "copy",
    "keys",
    "values",
    "items",
    "get",
    "update",
    "setdefault",
    "clear",
    "add",
    "remove",
    "discard",
    "union",
    "intersection",
    "difference",
    "join",
    "split",
    "strip",
    "lower",
    "upper",
    "replace",
    "find",
    "startswith",
    "endswith",
];

// JavaScript/TypeScript built-ins
const JS_BUILTINS: &[&str] = &[
    "console",
    "window",
    "document",
    "process",
    "require",
    "module",
    "exports",
    "Promise",
    "Array",
    "Object",
    "String",
    "Number",
    "Boolean",
    "Function",
    "RegExp",
    "Date",
    "Error",
    "Math",
    "JSON",
    "Map",
    "Set",
    "WeakMap",
    "WeakSet",
    "Symbol",
    "Proxy",
    "Reflect",
    "Intl",
    "NaN",
    "Infinity",
    "undefined",
    "parseInt",
    "parseFloat",
    "isNaN",
    "isFinite",
    "encodeURI",
    "decodeURI",
    "encodeURIComponent",
    "decodeURIComponent",
    "eval",
    "setTimeout",
    "setInterval",
    "clearTimeout",
    "clearInterval",
    "fetch",
    "await",
    "async",
    "let",
    "const",
    "class",
    "extends",
    "super",
    "this",
    "new",
    "typeof",
    "instanceof",
    "void",
    "delete",
    "throw",
    "try",
    "catch",
    "finally",
    "if",
    "else",
    "for",
    "while",
    "do",
    "switch",
    "case",
    "break",
    "continue",
    "return",
    "with",
    "try",
    "Buffer",
    "URL",
    "URLSearchParams",
    "Headers",
    "Request",
    "Response",
];

// Go built-ins
const GO_BUILTINS: &[&str] = &[
    "make", "new", "len", "cap", "append", "copy", "delete", "panic", "recover", "print",
    "println", "error", "true", "false", "iota", "nil", "append", "cap", "close", "complex",
    "imag", "real", "copy", "delete", "len", "make", "new", "panic", "recover", "append", "cap",
    "close", "complex", "imag", "real", "fmt", "os", "io", "net", "http", "json", "encoding",
    "log", "sync", "context", "time", "math", "strings", "strconv", "bytes", "bufio",
];

// Rust built-ins (prelude + std/core common items)
const RUST_BUILTINS: &[&str] = &[
    "Some",
    "None",
    "Ok",
    "Err",
    "true",
    "false",
    "std",
    "core",
    "alloc",
    "vec",
    "string",
    "stringify",
    "println",
    "eprintln",
    "print",
    "eprint",
    "format",
    "panic",
    "unreachable",
    "unimplemented",
    "todo",
    "assert",
    "assert_eq",
    "assert_ne",
    "debug_assert",
    "debug_assert_eq",
    "debug_assert_ne",
    "derive",
    "macro_rules",
    "use",
    "pub",
    "mod",
    "crate",
    "self",
    "super",
    "Option",
    "Result",
    "Vec",
    "String",
    "Vec",
    "HashMap",
    "HashSet",
    "Box",
    "Rc",
    "Arc",
    "Cell",
    "RefCell",
    "Mutex",
    "RwLock",
    "Condvar",
    "Drop",
    "Clone",
    "Copy",
    "PartialEq",
    "PartialOrd",
    "Eq",
    "Ord",
    "Default",
    "Debug",
    "Display",
    "Hash",
    "Borrow",
    "Into",
    "From",
    "Iterator",
    "IntoIterator",
    "Extend",
    "DoubleEndedIterator",
    "Future",
    "Async",
    "await",
    "yield",
];
